site_name: Aaron Cowley
nav: 
  - Home: index.md
  - Resume: AaronCowleyResume/AaronCowleyResume.pdf
  - Articles:
    - "Aaron Cowley BTFM": aaronBTFM/aaronBTFM.md
    - "Arch Linux Install Guide": articles/archlinuxinstall.md
theme: cyborg
